### ISSUE TITLE
🟨  [2-4] Stranger UNICT bot

### ISSUE THREAD

**Issue by Helias** [UNICT-Quality-Development/qd-projects-2022#12]
Questo progetto consiste nello sviluppo di un bot di Telegram che permette di parlare in maniera del tutto anonima con altri studenti UNICT.

**Come funziona?**
 Contattando il bot sarà possibile "iscriversi" inserendo la propria email universitaria e dopo una verifica via e-mail sarà possibile conversare con un altro studente in forma del tutto anonima, inoltre la scelta dell'interlocutore sarà del tutto casuale.

Bonus feature:
- poter segnalare l'interlocutore
- ..... altre funzionalità verranno aggiunte in base alla quantità di partecipanti....

---

Il progetto dovrà prevedere una pipeline tramite le GitHub Action e lo sviluppo di unit-test mediante il framework pytest raggiungendo una code coverage del 75%.

---

Questo progetto è di iniziativa dell'utente @InfraBlue0, per chi fosse interessato commenti qui sotto!

**Comment by Furankolin** [comment]
Buon pomeriggio, mi propongo per questo progetto

**Comment by MeloFuccio** [comment]
Salve,  sono interessato al progetto.
