### ISSUE TITLE
🤝 [2] Sorteggio bot

### ISSUE THREAD

**Issue by carme-10** [UNICT-Quality-Development/qd-projects-2022#14]
Questo progetto consisterà nel realizzare un bot di telegram che permetta di sorteggiare randomicamente un numero scelto di utenti presenti in un gruppo. 
Il sorteggio sarà possibile effettuarlo nelle seguenti modalità:
-Includere tutti gli utenti del gruppo 
-Includere solo gli amministratori 
-Includere solo gli utenti non amministratori 
-Includere solo degli utenti specifici, che verranno specificati manualmente

Progetto assegnato a:  @salvo-polizzi  @melit0

**Comment by salvo-polizzi** [comment]
Link repository: https://github.com/salvo-polizzi/Sorteggio-Bot
