### ISSUE TITLE
🤝  [2] My Personal Diet

### ISSUE THREAD

**Issue by Svemilio** [UNICT-Quality-Development/qd-projects-2022#15]
Questo progetto consisterà in un programma che permetta di creare
una propria dieta personale ,fornendo dei dati personali come: 
-Genere
-Altezza 
-Peso
-Minuti settimanali di attività fisica
-Obiettivo da raggiungere.
I risultati che il programma restituirà saranno  generali ma, più veritieri possibili grazie ad appositi calcoli.
i risultati restituiti indicheranno i carboidrati, grassi e proteine da assumere giornalmente e quanta attività fisica bisogna svolgere settimanalmente!

Progetto assegnato a @Svemilio @carlospata

**Comment by carlospata** [comment]
Link repo: 
https://github.com/carlospata/my-personal-diet

**Comment by Helias** [comment]
Ottimo progetto 🚀
