### ISSUE TITLE
🤝  [4] Gioco dell'impiccato

### ISSUE THREAD

**Issue by Graziano01** [UNICT-Quality-Development/qd-projects-2022#17]
Questo progetto consiste nello sviluppare il gioco dell'impiccato interamente in python. 
Verranno implementate le seguenti funzionalità:

- Interfaccia grafica con menù principale;
- Gioco principale con diverse difficoltà;
- Gioco personalizzato per scegliere la categoria delle parole;
- Sistema di registrazione/login degli utenti;
- Classifica con punteggio.

Eventuali altre feature verranno implementate.

Progetto assegnato a @Graziano01 @Giovanniprevitera01 @fross29 @Giovannicampo

Link repository: https://github.com/Graziano01/HangmanGame
Edit: la vecchia repository è stata cancellata e ricreata, il link rimane lo stesso

**Comment by Helias** [comment]
tagga tutti i partecipanti e metti il link della repository se l'avete già creata
