### ISSUE TITLE
🤝 [3] Discord Images/GIFs Bot

### ISSUE THREAD

**Issue by babilkebab** [UNICT-Quality-Development/qd-projects-2022#18]
Il progetto consiste nella creazione di un bot discord utilizzando il linguaggio python e la libreria discord.py (https://discordpy.readthedocs.io/en/stable/).
Il bot avrà due funzioni:

1.    Ricerca di un’immagine tramite un Custom Search Engine di Google che sfrutta Google Immagini. Utilizzeremo le Custom Search JSON API di Google che permettono un massimo di 100 queries/giorno con la licenza gratuita.
https://developers.google.com/custom-search/v1/introduction
2.    Ricerca di una GIF su GIPHY tramite le API di GIPHY stesso. Nella versione con licenza gratuita permettono un massimo di 1000 queries/giorno.
https://developers.giphy.com/

Progetto assegnato a @babilkebab @tuppulix @SpataMassimo
Link repo: https://github.com/babilkebab/Discord-Images-GIFs-Bot

**Comment by SpataMassimo** [comment]
Buona sera, vorrei unirmi al progetto.
