### ISSUE TITLE
🤝  [1] Snake_Game

### ISSUE THREAD

**Issue by Nemoraffa** [UNICT-Quality-Development/qd-projects-2022#20]
Questo progetto consiste nello sviluppare una versione moderna del famoso videogioco Snake interamente in Python.

**Funzionalità:**
- Interfaccia grafica (menù principale incluso);
- Classico Snake dal punto di vista di gameplay ma con diverse difficoltà;
- Highscore per ogni livello di difficoltà.

~~Progetto assegnato a @Nemoraffa , @massacrator340 e @aledialessandra.~~
[**LINK REPOSITORY**](https://github.com/Nemoraffa/snake_game)

**Comment by Piccions97** [comment]
Vorrei partecipare al progetto
