### ISSUE TITLE
🤝  [2] Welcome Bot & Healthcheck bot

### ISSUE THREAD

**Issue by Helias** [UNICT-Quality-Development/qd-projects-2022#5]
Questo "progetto QD" consiste nello sviluppare parallelamente due mini-progetti molto semplici:

### Welcome Bot
Telegram bot da realizzare mediante l'uso della libreria python-telegram-bot. Questo bot consiste nell'inviare un messaggio randomizzato tra una lista di messaggi presenti all'interno del bot, ogni qualvolta un nuovo utente entra in uno specifico gruppo Telegram.

### Healthcheck bot
Questo progetto consiste nel creare uno script python che verifichi se un determinato servizio (sito web o altro) è "attivo/online", nel momento in cui il servizio sarà "down" dovrà effettuare una chiamata HTTP alle API di Telegram al fine di inviare un messaggio su una specifica chat telegram (canale / gruppo / utente).

--- 

Questi mini-progetti saranno svolti in due repository diverse ma entrambi gli studenti dovranno contribuire al loro sviluppo mediante Pull Request e revisionando continuamente il codice di entrambi i progetti.
Ogni mini-progetto dovrà comprendere pipeline, unit-test al fine di raggiungere una **code coverage del 100%**.

---

Questo progetto è stato assegnato, link repositories: https://github.com/QD-2022

**Comment by Valeri0p** [comment]
@domenicoblanco ed io ( @Valeri0p ) ci proponiamo per questo progetto.

**Comment by Valeri0p** [comment]
Completati :D
