### ISSUE TITLE
🤝  [2] Sanremo ranking

### ISSUE THREAD

**Issue by Helias** [UNICT-Quality-Development/qd-projects-2022#7]
Creare un programma in python che permetta di:
- visualizzare la classifica di Sanremo in uno specifico anno (2022, 2021, 2019 ecc.)
- visualizzare link youtube di ogni canzone della classifica
- visualizzare link di youtube e testo della canzone di ogni classifica

Bonus feature:
- interfaccia grafica
- mostrare all'interno dell'interfaccia grafica un player per ascoltare le canzoni e/o visualizzare il video

--- 

Il progetto dovrà prevedere una pipeline tramite le GitHub Action e lo sviluppo di unit-test mediante il framework pytest raggiungendo una code coverage del 75%.

---

Questo progetto è stato assegnato a due studenti

**Comment by DenyR96** [comment]
https://github.com/DenyR96/Sanremo-ranking.git
Questo è il link della repository del progetto.
